### ISSUE TITLE
Project Review

### ISSUE THREAD

**Issue by jordanwillis** [GY1970/sql-scratch-capstone-turn-in#1]
### Criteria 1: Report: Are conclusions clear and supported by evidence in all eight answers?
* _Score Level:_ 2/4
* _Comment(s):_ Nice job creating a very well put together presentation.  In general everything looked good and queries and data were provided for their corresponding slides.  There were a few slides that I had expected to find some data, however the data tables were empty.

One thing that I did not find in the presentation was your data analysis and conclusions about the result of the A/B home try on test (e.g. does 3 pairs result in more purchases or does 5 pairs?).  You did provide a good start to this analysis in section 3, but never went anywhere with it in order to answer question #4 and #5 from the requirements.  This included creating the new table showing `is_home_try_on`, `number_of_pairs`, and `is_purchased` for each user.  You can then use this table to analyze if 3 or 5 try on pairs are better.  On a side note, I did find your query to create this table in your `code.sql` file, just no mention of it in the analysis.

Lastly, I would have liked to see some more analysis and conclusions at the end that address question #6 from the requirements.  Things like calculating overall conversation rates, most popular models or colors, difference purchase rates between the 3 and 5 pair try on, etc.
 
### Criteria 2: Query Accuracy: Do queries do what they were supposed to do?
* _Score Level:_ 4/4
* _Comment(s):_ All of the queries that I reviewed in your `code.sql` produced correct results!  Nice work!
 
### Criteria 3: Query Formatting
* _Score Level:_ 4/4
* _Comment(s):_ Your formatting looked pretty good, but be sure to keep the style guide handy for future projects.

https://s3.amazonaws.com/codecademy-content/programs/learn-sql-from-scratch/SQL+Style+Guide+for+Learn+SQL+from+Scratch.pdf
 
### Criteria 4: Understanding underlying concepts and terminology
* _Score Level:_ 4/4
* _Comment(s):_ It was pretty clear that you have a good understanding of the key concepts and terminology at play in the project!

 ### Overall Score: 14/16
Overall you did a pretty good job on this project!  Be sure to read my comments above, but I think you could further improve things by including some actual data on some slides and being sure to perform all the necessary data analysis.  Remember that the end goal in all of this is to ultimately come up with some actionable data insights that "pretend" business leaders can use to improve their business.

Keep up the great work!

**Comment by GY1970** [comment]
Mr. Willis,
Thank you very much for the time and effort to review my project.  I truly appreciate your constructive comments and will take them to heart.  It's true; the results could have yielded better substance to the presentation had I spent more time really analyzing the data to produce concrete "actionable" conclusions of the analysis using learned SQL concepts.  I look forward to continue the learning process.  Take Care.
-Glenn
